project:
  type: website
  output-dir: docs

website:
  title: "Rstudio Scripts"
  navbar:
    left:
    - href: index.qmd
      text: Inici
    - href: basics.qmd
      text: Basics
    - href: estadistica.qmd
      text: Estadística
    - href: grafics.qmd
      text: Gràfics
    - href: quarto.qmd
      text: Quarto
    - href: final.qmd
      text: Final

format:
  html:
    toc: true
    toc-depth: 3

